# Generated by Django 5.1 on 2026-06-01 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_expand_weatherrecord'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='weatherrecord',
            new_name='api_weather_recorde_cd993d_idx',
            old_name='api_weather_recorded_idx',
        ),
        migrations.RenameIndex(
            model_name='weatherrecord',
            new_name='api_weather_locatio_4be9c5_idx',
            old_name='api_weather_location_recorded_idx',
        ),
    ]
